# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfxunpack < Formula
  desc "Build kustomize overlays with flux2 HelmRelease support"
  homepage "https://github.com/DoodleScheduling/tfxunpack"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.1.1/tfxunpack_0.1.1_darwin_amd64.tar.gz"
      sha256 "8a64b96c837a2b36b980d355a635ee2e1421f29ebb4d5f10c0f9b90325e1bc32"

      def install
        bin.install "tfxunpack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.1.1/tfxunpack_0.1.1_darwin_arm64.tar.gz"
      sha256 "df6154eae44d256371a665e1e53c0841adec10e21127199fe61a8ab22d6a278a"

      def install
        bin.install "tfxunpack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.1.1/tfxunpack_0.1.1_linux_amd64.tar.gz"
      sha256 "63c52751ae3a22c02fb0fa84c1210b3e334eb1b3287173f69c1bcfbb1d3325a8"
      def install
        bin.install "tfxunpack"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.1.1/tfxunpack_0.1.1_linux_arm64.tar.gz"
      sha256 "98e988feb05a1086194f99fb378b06ce9f4becf513ca40a51d5f17ef901a4e59"
      def install
        bin.install "tfxunpack"
      end
    end
  end

  test do
    system "#{bin}/tfxunpack -h"
  end
end
