# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfxunpack < Formula
  desc "Extract crossplane resources"
  homepage "https://github.com/DoodleScheduling/tfxunpack"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.0.1/tfxunpack_0.0.1_darwin_amd64.tar.gz"
      sha256 "ad0a0a6e0f41e79d6383b2456ac98566084d16f05ec154961a921e05ef2e49a8"

      def install
        bin.install "tfxunpack"
      end
    end
    on_arm do
      url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.0.1/tfxunpack_0.0.1_darwin_arm64.tar.gz"
      sha256 "5b93b4342da731792ec21a203d7a4bcf9539c9c347424a84f4e549ea728bdfd7"

      def install
        bin.install "tfxunpack"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.0.1/tfxunpack_0.0.1_linux_amd64.tar.gz"
        sha256 "5b394bdd1b5e03efd7b963f63b32c5118cc7c92b6c276fe85d699199c41301c7"

        def install
          bin.install "tfxunpack"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/tfxunpack/releases/download/v0.0.1/tfxunpack_0.0.1_linux_arm64.tar.gz"
        sha256 "4906797b8b80dd68e8d9d8eb3f9e34d129b679ef4b459cb1ffbeb58b63b6410a"

        def install
          bin.install "tfxunpack"
        end
      end
    end
  end

  test do
    system "#{bin}/tfxunpack -h"
  end
end
